config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users do
      member do
        get :following, :followers
      end
    end
    
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/home',    :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Sobre", about_path %></li>
	  <li><%= link_to "Contatos", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Novo</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Principal", root_path %></li>
      <% if signed_in? %>
	  <li><%= link_to "Usuarios", users_path %></li>
      <li><%= link_to "Perfil", current_user %></li>
	  <li><%= link_to "Configurações", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Ajuda", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Sair", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Entrar", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'print',  :media => 'print' %>
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
	<%= javascript_include_tag :defaults %>
  </head>
  <body>
     <div class="container">
      <%= render 'layouts/header' %>
     <section class="round">
	        <% flash.each do |key, value| %>
	          <div class="flash <%= key %>"><%= value %></div>
	        <% end %>
	        <%= yield %>
	 </section>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>